"""empty message

Revision ID: 23f19bfbb576
Revises: 829fa62a4af4
Create Date: 2020-12-31 22:42:51.392870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f19bfbb576'
down_revision = '829fa62a4af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book', sa.Column('readpage', sa.Integer(), nullable=True))
    op.add_column('user_book', sa.Column('totalpage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_book', 'totalpage')
    op.drop_column('user_book', 'readpage')
    # ### end Alembic commands ###
