"""empty message

Revision ID: 6f0341b96cde
Revises: 237403402d6f
Create Date: 2020-12-27 20:02:34.077116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0341b96cde'
down_revision = '237403402d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_book',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['books.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid', 'bid')
    )
    op.create_table('user_books_tags',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('tn', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['books.id'], ),
    sa.ForeignKeyConstraint(['tn'], ['tags.name'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid', 'bid', 'tn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_books_tags')
    op.drop_table('user_book')
    op.drop_table('tags')
    op.drop_table('books')
    # ### end Alembic commands ###
